name: Test

on:
  push:
    branches:
      - develop
    paths:
      - 'app/src/main/java/com/sample/screenshottest/a/**'
jobs:
  check-path-change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show message
        run: echo "워크 플로우 실행 성공"
